/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as ChamberRouteImport } from './routes/chamber'
import { Route as FieldRouteImport } from './routes/field'
import { Route as PatternRouteImport } from './routes/pattern'
import { Route as TickerRouteImport } from './routes/ticker'
import { Route as AgentsIdRouteImport } from './routes/agents_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const ChamberRoute = ChamberRouteImport.update({
  id: '/chamber',
  path: '/chamber',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldRoute = FieldRouteImport.update({
  id: '/field',
  path: '/field',
  getParentRoute: () => rootRouteImport,
} as any)
const PatternRoute = PatternRouteImport.update({
  id: '/pattern',
  path: '/pattern',
  getParentRoute: () => rootRouteImport,
} as any)
const TickerRoute = TickerRouteImport.update({
  id: '/ticker',
  path: '/ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIdRoute = AgentsIdRouteImport.update({
  id: '/agents_/$id',
  path: '/agents/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/chamber': typeof ChamberRoute
  '/field': typeof FieldRoute
  '/pattern': typeof PatternRoute
  '/ticker': typeof TickerRoute
  '/agents/$id': typeof AgentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/chamber': typeof ChamberRoute
  '/field': typeof FieldRoute
  '/pattern': typeof PatternRoute
  '/ticker': typeof TickerRoute
  '/agents/$id': typeof AgentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/chamber': typeof ChamberRoute
  '/field': typeof FieldRoute
  '/pattern': typeof PatternRoute
  '/ticker': typeof TickerRoute
  '/agents_/$id': typeof AgentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/chamber'
    | '/field'
    | '/pattern'
    | '/ticker'
    | '/agents/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/chamber'
    | '/field'
    | '/pattern'
    | '/ticker'
    | '/agents/$id'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/chamber'
    | '/field'
    | '/pattern'
    | '/ticker'
    | '/agents_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  ChamberRoute: typeof ChamberRoute
  FieldRoute: typeof FieldRoute
  PatternRoute: typeof PatternRoute
  TickerRoute: typeof TickerRoute
  AgentsIdRoute: typeof AgentsIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chamber': {
      id: '/chamber'
      path: '/chamber'
      fullPath: '/chamber'
      preLoaderRoute: typeof ChamberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field': {
      id: '/field'
      path: '/field'
      fullPath: '/field'
      preLoaderRoute: typeof FieldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pattern': {
      id: '/pattern'
      path: '/pattern'
      fullPath: '/pattern'
      preLoaderRoute: typeof PatternRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticker': {
      id: '/ticker'
      path: '/ticker'
      fullPath: '/ticker'
      preLoaderRoute: typeof TickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents_/$id': {
      id: '/agents_/$id'
      path: '/agents/$id'
      fullPath: '/agents/$id'
      preLoaderRoute: typeof AgentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  ChamberRoute: ChamberRoute,
  FieldRoute: FieldRoute,
  PatternRoute: PatternRoute,
  TickerRoute: TickerRoute,
  AgentsIdRoute: AgentsIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
