#!/usr/bin/env python3
"""Regenerate everything on the site that is derived from somewhere else.

Nothing here is edited by hand:

  * system.prompt.md  <- ../terminal/system.prompt.md   (canonical prompt)
  * index.html        <- data/agents.json               (roster fallback cards)
  * llms.txt          <- data/agents.json               (the "## Agents" block)
  * llms-full.txt     <- llms.txt + prompt + skill      (one-fetch bundle)

The prompt used to be pasted into index.html as a <pre> block; it drifted to a
truncated copy, and an agent wanting it had to scrape HTML. It is now published
raw at /system.prompt.md and merely linked from the page.

    python build.py
"""
from __future__ import annotations

import html
import json
import pathlib
import re
import shutil
import sys

HERE = pathlib.Path(__file__).parent
REPO = HERE.parent

PROMPT_SRC = REPO / "terminal" / "system.prompt.md"
PROMPT_OUT = HERE / "system.prompt.md"

AGENTS = json.loads((HERE / "data" / "agents.json").read_text(encoding="utf-8"))


# ── prompt ────────────────────────────────────────────────────────────────────

def sync_prompt() -> None:
    if not PROMPT_SRC.exists():
        sys.exit(f"missing canonical prompt: {PROMPT_SRC}")
    shutil.copyfile(PROMPT_SRC, PROMPT_OUT)
    print(f"system.prompt.md: {PROMPT_OUT.stat().st_size} bytes from {PROMPT_SRC.relative_to(REPO)}")


# ── roster ────────────────────────────────────────────────────────────────────

def card(a: dict) -> str:
    e = lambda k: html.escape(str(a.get(k, "")), quote=False)
    tier = a["tier"].lower()
    live = ' <span class="agent-live" title="Live on the mesh">●</span>' if a.get("live") else ""
    return f"""        <div class="agent-card {tier}">
          <div class="agent-tier">{e('tier')}{live}</div>
          <h3>{e('name')}</h3>
          <p>{e('desc')}</p>
          <div class="agent-meta"><span>{e('host')}</span><span>{e('stack')}</span></div>
          <div class="agent-dim">{e('dimension')}</div>
        </div>"""


def sync_html() -> None:
    path = HERE / "index.html"
    src = path.read_text(encoding="utf-8")
    cards = "\n".join(card(a) for a in AGENTS["agents"])
    body = (
        "<!-- AGENTS:BEGIN generated by build.py from data/agents.json "
        f"— edit the JSON, not this -->\n{cards}\n        <!-- AGENTS:END -->"
    )
    new, n = re.subn(r"<!-- AGENTS:BEGIN.*?AGENTS:END -->", body, src, flags=re.S)
    if n != 1:
        sys.exit("index.html: expected exactly one AGENTS:BEGIN/END region, found %d" % n)
    intro, n = re.subn(
        r'(<div class="swarm-intro">\s*<p>)[^<]*(</p>)',
        lambda m: m.group(1) + html.escape(AGENTS["summary"]) + m.group(2),
        new,
    )
    if n != 1:
        sys.exit("index.html: could not locate the .swarm-intro paragraph")
    path.write_text(intro, encoding="utf-8", newline="")
    print(f"index.html: {len(AGENTS['agents'])} cards")


def sync_llms() -> None:
    path = HERE / "llms.txt"
    src = path.read_text(encoding="utf-8")
    lines = []
    for a in AGENTS["agents"]:
        anchor = a.get("link", "https://redacted.meme/#swarm")
        state = "live on the mesh" if a.get("live") else a["host"]
        lines.append(f"[{a['name']}]({anchor}): {a['desc']} ({state}; {a['stack']})")
    block = "## Agents\n\n" + "\n".join(lines) + "\n"
    new, n = re.subn(r"## Agents\n\n(?:.+\n)+?\n", block + "\n", src, count=1)
    if n != 1:
        sys.exit("llms.txt: could not locate the '## Agents' block")
    path.write_text(new, encoding="utf-8", newline="")
    print(f"llms.txt: {len(AGENTS['agents'])} agents")


# ── one-fetch bundle ──────────────────────────────────────────────────────────

def build_llms_full() -> None:
    """llms.txt with the linked markdown inlined, per the llms.txt convention."""
    index = (HERE / "llms.txt").read_text(encoding="utf-8").rstrip()
    parts = [index, ""]
    for title, rel in (("System prompt", "system.prompt.md"), ("Terminal skill", "skill.md")):
        body = (HERE / rel).read_text(encoding="utf-8").rstrip()
        parts += [
            "",
            "=" * 78,
            f"# {title} — https://redacted.meme/{rel}",
            "=" * 78,
            "",
            body,
        ]
    out = HERE / "llms-full.txt"
    out.write_text("\n".join(parts) + "\n", encoding="utf-8", newline="")
    print(f"llms-full.txt: {out.stat().st_size} bytes")


if __name__ == "__main__":
    sync_prompt()
    sync_html()
    sync_llms()
    build_llms_full()
