#!/usr/bin/env python3
"""Regenerate the agent roster from data/agents.json.

`data/agents.json` is the single source of truth for the swarm roster. This script
syncs the two places that mirror it:

  * index.html  — the no-JS fallback cards between AGENTS:BEGIN / AGENTS:END
  * llms.txt    — the "## Agents" block

script.js re-renders the same cards client-side from the JSON at runtime, so the
fallback only ever shows if the fetch fails. Run this after editing agents.json:

    python build.py
"""
from __future__ import annotations

import html
import json
import pathlib
import re
import sys

HERE = pathlib.Path(__file__).parent
AGENTS = json.loads((HERE / "data" / "agents.json").read_text(encoding="utf-8"))


def card(a: dict) -> str:
    e = lambda k: html.escape(str(a.get(k, "")), quote=False)
    tier = a["tier"].lower()
    live = ' <span class="agent-live" title="Live on the mesh">●</span>' if a.get("live") else ""
    return f"""        <div class="agent-card {tier}">
          <div class="agent-tier">{e('tier')}{live}</div>
          <h3>{e('name')}</h3>
          <p>{e('desc')}</p>
          <div class="agent-meta"><span>{e('host')}</span><span>{e('stack')}</span></div>
          <div class="agent-dim">{e('dimension')}</div>
        </div>"""


def sync_html() -> None:
    path = HERE / "index.html"
    src = path.read_text(encoding="utf-8")
    cards = "\n".join(card(a) for a in AGENTS["agents"])
    body = f"<!-- AGENTS:BEGIN generated by build.py from data/agents.json — edit the JSON, not this -->\n{cards}\n        <!-- AGENTS:END -->"
    new, n = re.subn(
        r"<!-- AGENTS:BEGIN.*?AGENTS:END -->", body, src, flags=re.S
    )
    if n != 1:
        sys.exit("index.html: expected exactly one AGENTS:BEGIN/END region, found %d" % n)
    intro, n = re.subn(
        r'(<div class="swarm-intro">\s*<p>)[^<]*(</p>)',
        lambda m: m.group(1) + html.escape(AGENTS["summary"]) + m.group(2),
        new,
    )
    if n != 1:
        sys.exit("index.html: could not locate .swarm-intro paragraph")
    path.write_text(intro, encoding="utf-8", newline="")
    print(f"index.html: {len(AGENTS['agents'])} cards")


def sync_llms() -> None:
    path = HERE / "llms.txt"
    src = path.read_text(encoding="utf-8")
    lines = []
    for a in AGENTS["agents"]:
        anchor = a.get("link", "https://redacted.meme/#swarm")
        state = "live on the mesh" if a.get("live") else a["host"]
        lines.append(f"[{a['name']}]({anchor}): {a['desc']} ({state}; {a['stack']})")
    block = "## Agents\n\n" + "\n".join(lines) + "\n"
    new, n = re.subn(r"## Agents\n\n(?:.+\n)+?\n", block + "\n", src, count=1)
    if n != 1:
        sys.exit("llms.txt: could not locate the '## Agents' block")
    path.write_text(new, encoding="utf-8", newline="")
    print(f"llms.txt: {len(AGENTS['agents'])} agents")


if __name__ == "__main__":
    sync_html()
    sync_llms()
